core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('courses/', include('courses.urls', namespace="courses")),
    path('payment/', include('payment.urls', namespace="payment")),

    path('', HomeView.as_view(), name="home")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

payment/urls.py
from django.urls import path
from .views import PricingView, PaymentView
app_name="payment"

urlpatterns = [
     path('pricing/', PricingView.as_view(), name="pricing"),
     path('pricing/<slug>/', PaymentView.as_view(), name="payment"),
    
]

payment/models.py
from django.db import models

# Create your models here.

payment/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic.base import View
from django.conf import settings
from courses.models import Pricing



# Create your views here.
class PricingView(View):
    def get(self, request, *args, **kwargs):
        context={
            
        }
        return render(request, 'payments/pricing.html', context)

class PaymentView(View):
    def get(self, request, slug,*args, **kwargs):
        pricing = get_object_or_404(Pricing, slug=slug)

       

        context={
            'pricing_tier':pricing,
            "STRIPE_PUBLIC_KEY": settings.STRIPE_PUBLIC_KEY
        }
        
        return render(request, 'payments/checkout.html', context)

       

templates/payments/change.html
{% extends "base.html" %}
{% load static %}
{% load tailwind_tags %}
{% load tailwind_filters %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'css/stripe.css' %}" />
{% endblock extra_head %}

{% block navbar %}
{% include 'components/navbar.html' %}
{% endblock navbar %}

{% block content %}
  <div class="flex justify-center mx-auto">
    <div class="py-3">

      <div class="border dark:border-dark-third border-gray-200 rounded shadow-md px-3 py-3">
        <h2 class="text-xl text-center text-gray-500">
          Change to the {{ pricing_tier.name }} membership
        </h2>
        <p class="text-3xl text-center text-gray-800">
          {% if pricing_tier.currency == "usd" %}
          ${{ pricing_tier.price }}/mo
          {% else %}
          €{{ pricing_tier.price }}/mo
          {% endif %}
        </p>
      </div>

      <div class="mt-3">
        <form id="change-form">
          {% csrf_token %}
          <button id="submit" type="submit">
              <div class="spinner hidden" id="spinner"></div>
              <span id="button-text">Buy Now</span>
          </button>
        </form>
      </div>

    </div>
  </div>
{% endblock content %}


 
{% block javascript %}
<script>
  const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;

  function updateSubscription(priceId, subscriptionId) {
    return fetch("{% url 'payment:change-subscription' %}", {
      method: 'post',
      headers: {
        'Content-type': 'application/json',
        'X-CSRFToken': csrftoken
      },
      body: JSON.stringify({
        priceId: "{{ pricing_tier.stripe_price_id }}",
      }),
    })
      .then(response => {
        return response.json();
      })
      .then(response => {
        window.location.href = "{% url 'user:subscription' request.user.username %}"
        return response;
      });
  }

  function changeLoadingState(isLoading) {
    if (isLoading) {
      document.querySelector('#button-text').classList.add('hidden');
      document.querySelector('#spinner').classList.remove('hidden');
      document.querySelector('#change-form button').disabled = true;
    } else {
      document.querySelector('#button-text').classList.remove('hidden');
      document.querySelector('#spinner').classList.add('hidden');
      document.querySelector('#change-form button').disabled = false;
    }
  }

  var form = document.getElementById('change-form');

  form.addEventListener('submit', function (ev) {
    ev.preventDefault();
    changeLoadingState(true);
    updateSubscription()
  });
</script>
{% endblock javascript %}

templates/payments/pricing.html
{% extends 'base.html' %}

{% block title %}{% endblock title %}
{% block extra_head %}{% endblock extra_head %}


{% block navbar %}
{% include 'components/navbar.html' %}
{% endblock navbar %}


{% block content %}

<!-- This example requires Tailwind CSS v2.0+ -->
<div class="bg-gray-100">

  <div class="pt-12 sm:pt-16 lg:pt-20">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="text-center">
        <h2 class="text-3xl font-extrabold text-gray-900 sm:text-4xl lg:text-5xl">
          Pricing
        </h2>
        <p class="mt-4 text-xl text-gray-600">
          Choose from our payment options
        </p>
      </div>
    </div>
  </div>

  <div class="mt-8 bg-white pb-16 sm:mt-12 sm:pb-20 lg:pb-28">
    <div class="relative">
      <div class="absolute inset-0 h-1/2 bg-gray-100"></div>
      <div class="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="max-w-lg mx-auto rounded-lg shadow-lg overflow-hidden lg:max-w-none lg:flex">
          <div class="flex-1 bg-white px-6 py-8 lg:p-12">
            <h3 class="text-2xl font-extrabold text-gray-900 sm:text-3xl">
              Membresia Pro
            </h3>
            <p class="mt-6 text-base text-gray-500">
              Acceso a todos los cursos de la plataforma
            </p>
            <div class="mt-8">
              <div class="flex items-center">
                <h4 class="flex-shrink-0 pr-4 bg-white text-sm tracking-wider font-semibold uppercase text-indigo-600">
                  What's included
                </h4>
                <div class="flex-1 border-t-2 border-gray-200"></div>
              </div>
              <ul role="list" class="mt-8 space-y-5 lg:space-y-0 lg:grid lg:grid-cols-2 lg:gap-x-8 lg:gap-y-5">
                <li class="flex items-start lg:col-span-1">
                  <div class="flex-shrink-0">
                    <!-- Heroicon name: solid/check-circle -->
                    <svg class="h-5 w-5 text-green-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                      <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
                    </svg>
                  </div>
                  <p class="ml-3 text-sm text-gray-700">
                    Private forum access
                  </p>
                </li>

                <li class="flex items-start lg:col-span-1">
                  <div class="flex-shrink-0">
                    <!-- Heroicon name: solid/check-circle -->
                    <svg class="h-5 w-5 text-green-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                      <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
                    </svg>
                  </div>
                  <p class="ml-3 text-sm text-gray-700">
                    Member resources
                  </p>
                </li>

                <li class="flex items-start lg:col-span-1">
                  <div class="flex-shrink-0">
                    <!-- Heroicon name: solid/check-circle -->
                    <svg class="h-5 w-5 text-green-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                      <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
                    </svg>
                  </div>
                  <p class="ml-3 text-sm text-gray-700">
                    Entry to annual conference
                  </p>
                </li>

                <li class="flex items-start lg:col-span-1">
                  <div class="flex-shrink-0">
                    <!-- Heroicon name: solid/check-circle -->
                    <svg class="h-5 w-5 text-green-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                      <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
                    </svg>
                  </div>
                  <p class="ml-3 text-sm text-gray-700">
                    Official member t-shirt
                  </p>
                </li>
              </ul>
            </div>
          </div>

          <div class="py-8 px-6 text-center bg-gray-50 lg:flex-shrink-0 lg:flex lg:flex-col lg:justify-center lg:p-12">
            <p class="text-lg leading-6 font-medium text-gray-900">
              Pago mensual
            </p>
            <div class="mt-4 flex items-center justify-center text-5xl font-extrabold text-gray-900">
              <span>
                $20.00
              </span>
              <span class="ml-3 text-xl font-medium text-gray-500">
                MXN
              </span>
            </div>
            <p class="mt-4 text-sm">
              <a href="#" class="font-medium text-gray-500 underline">
                Nuestros terminos y condiciones de uso
              </a>
            </p>
            <div class="mt-6">
              <div class="rounded-md shadow">
                <a href="{% url 'payment:payment' 'free'  %}" class="flex items-center justify-center px-5 py-3 border border-transparent text-base font-medium rounded-md text-white bg-green-500 hover:bg-green-600">
                  Obtener acceso
                </a>
              </div>
            </div>
            <div class="mt-4 text-sm">
                <span class="cursor-default inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-gray-100 text-gray-800">
                Cancela cuando quieras
                </span>
            </div>
          </div>
        </div>

        <div class="max-w-lg mx-auto rounded-lg shadow-lg overflow-hidden lg:max-w-none lg:flex">
          <div class="flex-1 bg-white px-6 py-8 lg:p-12">
            <h3 class="text-2xl font-extrabold text-gray-900 sm:text-3xl">
              Membresia Academia
            </h3>
            <p class="mt-6 text-base text-gray-500">
              Acceso a todos los cursos de la plataforma
            </p>
            <div class="mt-8">
              <div class="flex items-center">
                <h4 class="flex-shrink-0 pr-4 bg-white text-sm tracking-wider font-semibold uppercase text-indigo-600">
                  What's included
                </h4>
                <div class="flex-1 border-t-2 border-gray-200"></div>
              </div>
              <ul role="list" class="mt-8 space-y-5 lg:space-y-0 lg:grid lg:grid-cols-2 lg:gap-x-8 lg:gap-y-5">
                <li class="flex items-start lg:col-span-1">
                  <div class="flex-shrink-0">
                    <!-- Heroicon name: solid/check-circle -->
                    <svg class="h-5 w-5 text-green-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                      <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
                    </svg>
                  </div>
                  <p class="ml-3 text-sm text-gray-700">
                    Private forum access
                  </p>
                </li>

                <li class="flex items-start lg:col-span-1">
                  <div class="flex-shrink-0">
                    <!-- Heroicon name: solid/check-circle -->
                    <svg class="h-5 w-5 text-green-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                      <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
                    </svg>
                  </div>
                  <p class="ml-3 text-sm text-gray-700">
                    Member resources
                  </p>
                </li>

                <li class="flex items-start lg:col-span-1">
                  <div class="flex-shrink-0">
                    <!-- Heroicon name: solid/check-circle -->
                    <svg class="h-5 w-5 text-green-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                      <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
                    </svg>
                  </div>
                  <p class="ml-3 text-sm text-gray-700">
                    Entry to annual conference
                  </p>
                </li>

                <li class="flex items-start lg:col-span-1">
                  <div class="flex-shrink-0">
                    <!-- Heroicon name: solid/check-circle -->
                    <svg class="h-5 w-5 text-green-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                      <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
                    </svg>
                  </div>
                  <p class="ml-3 text-sm text-gray-700">
                    Official member t-shirt
                  </p>
                </li>
              </ul>
            </div>
          </div>

          <div class="py-8 px-6 text-center bg-gray-50 lg:flex-shrink-0 lg:flex lg:flex-col lg:justify-center lg:p-12">
            <p class="text-lg leading-6 font-medium text-gray-900">
              Pago mensual
            </p>
            <div class="mt-4 flex items-center justify-center text-5xl font-extrabold text-gray-900">
              <span>
                $97
              </span>
              <span class="ml-3 text-xl font-medium text-gray-500">
                USD
              </span>
            </div>
            <p class="mt-4 text-sm">
              <a href="#" class="font-medium text-gray-500 underline">
                Nuestros terminos y condiciones de uso
              </a>
            </p>
            <div class="mt-6">
              <div class="rounded-md shadow">
                <a href="{% url 'payment:payment' 'PRO'  %}" class="flex items-center justify-center px-5 py-3 border border-transparent text-base font-medium rounded-md text-white bg-green-500 hover:bg-green-600">
                  Obtener acceso
                </a>
              </div>
            </div>
            <div class="mt-4 text-sm">
                <span class="cursor-default inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-gray-100 text-gray-800">
                Cancela cuando quieras
                </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


</div>



{% endblock content %}
    

{% block footer %}

{% endblock footer %}

{% block javascript %}{% endblock javascript %}

templates/payments/thankyou.html
{% extends 'base.html' %}

{% block title %}{% endblock title %}
{% block extra_head %}{% endblock extra_head %}


{% block navbar %}
{% include 'components/navbar.html' %}
{% endblock navbar %}


{% block content %}

<!-- This example requires Tailwind CSS v2.0+ -->
gracias por tu compra


{% endblock content %}
    

{% block footer %}

{% endblock footer %}

{% block javascript %}{% endblock javascript %}