core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('courses/', include('courses.urls', namespace="courses")),
    path('payment/', include('payment.urls', namespace="payment")),

    path('', HomeView.as_view(), name="home")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

payment/urls.py
from django.urls import path
from .views import PricingView, PaymentView
app_name="payment"

urlpatterns = [
     path('pricing/', PricingView.as_view(), name="pricing"),
     path('pricing/<slug>/', PaymentView.as_view(), name="payment"),
    
]

templates/components/courses_navbar.html
<!-- This example requires Tailwind CSS v2.0+ -->
<nav x-data="{open:false}" class="bg-white shadow z-10">
    <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
      <div class="relative flex justify-between h-16">
        <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
          <!-- Mobile menu button -->
          <button @click="open=true" type="button" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500" aria-controls="mobile-menu" aria-expanded="false">
            <span class="sr-only">Open main menu</span>
            <!--
              Icon when menu is closed.
  
              Heroicon name: outline/menu
  
              Menu open: "hidden", Menu closed: "block"
            -->
            <svg class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
            </svg>
            <!--
              Icon when menu is open.
  
              Heroicon name: outline/x
  
              Menu open: "block", Menu closed: "hidden"
            -->
            <svg class="hidden h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
  
        <div class="flex-1 flex items-center justify-center sm:items-stretch sm:justify-start">
  
          <div class="flex-shrink-0 flex items-center">
              <a href="{% url 'home' %}" class="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
              Return
              </a>
          </div>
  
          <div class="hidden sm:ml-6 sm:flex sm:space-x-8">
            <!-- Current: "border-indigo-500 text-gray-900", Default: "border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700" -->
            <a href="#" class="border-indigo-500 text-gray-900 inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium">
              Dashboard
            </a>
            <a href="#" class="border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700 inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium">
              Team
            </a>
            <a href="#" class="border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700 inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium">
              Projects
            </a>
            <a href="#" class="border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700 inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium">
              Calendar
            </a>
          </div>
        </div>
  
      </div>
    </div>
  
    <!-- Mobile menu, show/hide based on menu state. -->
    <div x-show="open" @click.away="open=false" class="sm:hidden" id="mobile-menu">
      <div class="pt-2 pb-4 space-y-1">
        <!-- Current: "bg-indigo-50 border-indigo-500 text-indigo-700", Default: "border-transparent text-gray-500 hover:bg-gray-50 hover:border-gray-300 hover:text-gray-700" -->
        <a href="#" class="bg-indigo-50 border-indigo-500 text-indigo-700 block pl-3 pr-4 py-2 border-l-4 text-base font-medium">Dashboard</a>
        <a href="#" class="border-transparent text-gray-500 hover:bg-gray-50 hover:border-gray-300 hover:text-gray-700 block pl-3 pr-4 py-2 border-l-4 text-base font-medium">Team</a>
        <a href="#" class="border-transparent text-gray-500 hover:bg-gray-50 hover:border-gray-300 hover:text-gray-700 block pl-3 pr-4 py-2 border-l-4 text-base font-medium">Projects</a>
        <a href="#" class="border-transparent text-gray-500 hover:bg-gray-50 hover:border-gray-300 hover:text-gray-700 block pl-3 pr-4 py-2 border-l-4 text-base font-medium">Calendar</a>
      </div>
    </div>
  </nav>

templates/components/footer.html
<!-- This example requires Tailwind CSS v2.0+ -->
{% load static %}
<div x-data="{open:false}" class="relative bg-white z-10">
  <div class="flex justify-between items-center px-4 py-4 shadow sm:px-6 md:justify-start md:space-x-10">
    <div>
      <a href="{% url 'home' %}" class="flex">
        <span class="sr-only">Workflow</span>
        <img class="h-8 w-auto sm:h-10" src="https://tailwindui.com/img/logos/workflow-mark-indigo-600.svg" alt="">
      </a>
    </div>

    <div class="-mr-2 -my-2 md:hidden">
      <button @click="open=true" type="button" class="bg-white rounded-md p-2 inline-flex items-center justify-center text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500" aria-expanded="false">
        <span class="sr-only">Open menu</span>
        <!-- Heroicon name: outline/menu -->
        <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
        </svg>
      </button>
    </div>

    <div class="hidden md:flex-1 md:flex md:items-center md:justify-between">
      <nav class="flex space-x-10">
        
        <a href="{% url 'payment:pricing' %}" class="text-base font-medium text-gray-500 hover:text-gray-900">
          precios
        </a>

        <a href="#" class="text-base font-medium text-gray-500 hover:text-gray-900">
          Learn
        </a>

        <div x-data="{open:false}" class="relative">
          <!-- Item active: "text-gray-900", Item inactive: "text-gray-500" -->
          <button @click="open=true" type="button" class="text-gray-500 group bg-white rounded-md inline-flex items-center text-base font-medium hover:text-gray-900 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" aria-expanded="false">
            <span>cursos</span>
            <!--
              Heroicon name: solid/chevron-down

              Item active: "text-gray-600", Item inactive: "text-gray-400"
            -->
            <svg class="text-gray-400 ml-2 h-5 w-5 group-hover:text-gray-500" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
            </svg>
          </button>

          <div x-show="open" @click.away="open=false" class="absolute z-10 left-1/2 transform -translate-x-1/2 mt-3 px-2 w-screen max-w-xs sm:px-0">
            <div class="rounded-lg shadow-lg ring-1 ring-black ring-opacity-5 overflow-hidden">
              <div class="relative grid gap-6 bg-white px-5 py-6 sm:gap-8 sm:p-8">
                <a href="#" class="-m-3 p-3 block rounded-md hover:bg-gray-50">
                  <p class="text-base font-medium text-gray-900">
                    Help Center
                  </p>
                  <p class="mt-1 text-sm text-gray-500">
                    Get all of your questions answered in our forums or contact support.
                  </p>
                </a>

                <a href="#" class="-m-3 p-3 block rounded-md hover:bg-gray-50">
                  <p class="text-base font-medium text-gray-900">
                    Guides
                  </p>
                  <p class="mt-1 text-sm text-gray-500">
                    Learn how to maximize our platform to get the most out of it.
                  </p>
                </a>

                <a href="#" class="-m-3 p-3 block rounded-md hover:bg-gray-50">
                  <p class="text-base font-medium text-gray-900">
                    Events
                  </p>
                  <p class="mt-1 text-sm text-gray-500">
                    See what meet-ups and other events we might be planning near you.
                  </p>
                </a>

                <a href="#" class="-m-3 p-3 block rounded-md hover:bg-gray-50">
                  <p class="text-base font-medium text-gray-900">
                    Security
                  </p>
                  <p class="mt-1 text-sm text-gray-500">
                    Understand how we take your privacy seriously.
                  </p>
                </a>
              </div>
            </div>
          </div>
        </div>
      </nav>

      <div class="flex items-center md:ml-12">
        {% if user.is_authenticated %}
        <!-- This example requires Tailwind CSS v2.0+ -->
        <div x-data="{open:false}" class="relative inline-block text-left">
            <div @click="open=true">
                <img class="inline-block h-10 w-10 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
            </div>

            <div x-show="open" @click.away="open=false" class="origin-top-right absolute right-0 mt-2 w-56 rounded-md shadow-lg bg-white ring-1 ring-black ring-opacity-5 divide-y divide-gray-100 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="menu-button" tabindex="-1">
                <div class="px-4 py-3" role="none">
                <p class="text-sm" role="none">
                  Registrado como
                </p>
                <p class="text-sm font-medium text-gray-900 truncate" role="none">
                    tom@example.com
                </p>
                </div>
                <div class="py-1" role="none">
                <!-- Active: "bg-gray-100 text-gray-900", Not Active: "text-gray-700" -->
                <a href="{% url 'account_change_password' %}" class="text-gray-700 block px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="menu-item-0">Security</a>
                <a href="#" class="text-gray-700 block px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="menu-item-1">Support</a>
                <a href="{% url 'user:subscription' user.username %}" class="text-gray-700 block px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="menu-item-2">Subscription</a>
                </div>
                <div class="py-1" role="none">
                <form method="POST" action="{% url 'account_logout' %}" role="none">
                    {% csrf_token %}
                    <button type="submit" class="text-gray-700 block w-full text-left px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="menu-item-3">
                      desconectar
                    </button>
                </form>
                </div>
            </div>
        </div>

        {% else %}
        <a href="{% url 'account_login' %}" class="text-base font-medium text-gray-500 hover:text-gray-900">
          Sign in
        </a>
        <a href="{% url 'account_signup' %}" class="ml-8 inline-flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-indigo-600 hover:bg-indigo-700">
          Sign up
        </a>
        {% endif %}
        
      </div>

    </div>
  </div>

  <!--
    Mobile menu, show/hide based on mobile menu state.
  -->
  <div x-show="open" @click.away="open=false"
    x-transition:enter="ease-out duration-300" x-transition:enter-start="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95" x-transition:enter-end="opacity-100 translate-y-0 sm:scale-100" x-transition:leave="ease-in duration-200" x-transition:leave-start="opacity-100 translate-y-0 sm:scale-100" x-transition:leave-end="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
   class="absolute top-0 inset-x-0 p-2 transition transform origin-top-right md:hidden">
    <div class="rounded-lg shadow-lg ring-1 ring-black ring-opacity-5 bg-white divide-y-2 divide-gray-50">
      <div class="pt-5 pb-6 px-5">
        <div class="flex items-center justify-between">
          <div>
            <img class="h-8 w-auto" src="https://tailwindui.com/img/logos/workflow-mark-indigo-600.svg" alt="Workflow">
          </div>
          <div class="-mr-2">
            <button @click="open=false" type="button" class="bg-white rounded-md p-2 inline-flex items-center justify-center text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500">
              <span class="sr-only">Close menu</span>
              <!-- Heroicon name: outline/x -->
              <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
        </div>
        <div class="mt-6">
          <nav class="grid gap-6">
            <a href="#" class="-m-3 p-3 flex items-center rounded-lg hover:bg-gray-50">
              <div class="flex-shrink-0 flex items-center justify-center h-10 w-10 rounded-md bg-indigo-500 text-white">
                <!-- Heroicon name: outline/chart-bar -->
                <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
                </svg>
              </div>
              <div class="ml-4 text-base font-medium text-gray-900">
                Analytics
              </div>
            </a>


          </nav>
        </div>
      </div>
      <div class="py-6 px-5">
        <div class="grid grid-cols-2 gap-4">
          <a href="#" class="text-base font-medium text-gray-900 hover:text-gray-700">
            Pricing
          </a>

          <a href="#" class="text-base font-medium text-gray-900 hover:text-gray-700">
            Docs
          </a>

          <a href="#" class="text-base font-medium text-gray-900 hover:text-gray-700">
            Enterprise
          </a>

          <a href="#" class="text-base font-medium text-gray-900 hover:text-gray-700">
            Help Center
          </a>

          <a href="#" class="text-base font-medium text-gray-900 hover:text-gray-700">
            Guides
          </a>

          <a href="#" class="text-base font-medium text-gray-900 hover:text-gray-700">
            Events
          </a>

          <a href="#" class="text-base font-medium text-gray-900 hover:text-gray-700">
            Security
          </a>
        </div>
        <div class="mt-6">
          <a href="#" class="w-full flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-indigo-600 hover:bg-indigo-700">
            Sign up
          </a>
          <p class="mt-6 text-center text-base font-medium text-gray-500">
            Existing customer?
            <a href="#" class="text-indigo-600 hover:text-indigo-500">
              Sign in
            </a>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

templates/components/navbar.html
<!-- This example requires Tailwind CSS v2.0+ -->
{% load static %}
<div x-data="{open:false}" class="relative bg-black z-10">
 <div class="flex justify-between items-center px-4 py-4 shadow sm:px-6 md:justify-start md:space-x-10">
    <div>
      <a href="{% url 'home' %}" class="flex">
        <span class="sr-only">Workflow</span>
        <img class="h-8 w-auto sm:h-10" src="https://tailwindui.com/img/logos/workflow-mark-indigo-600.svg" alt="">
      </a>
    </div>

    <div class="-mr-2 -my-2 md:hidden">
      <button @click="open=true" type="button" class="bg-black rounded-md p-2 inline-flex items-center justify-center text-white hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500" aria-expanded="false">
        <span class="sr-only">abrir menu</span>
        <!-- Heroicon name: outline/menu -->
        <svg class="h-6 w-6 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
        </svg>
      </button>
    </div>

    <div class="hidden md:flex-1 md:flex md:items-center md:justify-between">
      <nav class="flex space-x-10">
        
        <a href="{% url 'payment:pricing' %}" class="text-base font-medium text-gray-500 hover:text-gray-900">
          precios
        </a>

        <a href="#" class="text-base font-medium text-white hover:text-gray-500">
          Learn
        </a>

        <div x-data="{open:false}" class="relative">
          <!-- Item active: "text-gray-900", Item inactive: "text-gray-500" -->
          <button @click="open=true" type="button" class="text-white group bg-black rounded-md inline-flex items-center text-base font-medium hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" aria-expanded="false">
            <span>cursos</span>
            <!--
              Heroicon name: solid/chevron-down

              Item active: "text-gray-600", Item inactive: "text-gray-400"
            -->
            <svg class="text-white ml-2 h-5 w-5 group-hover:text-gray-500" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
            </svg>
          </button>

          <div x-show="open" @click.away="open=false" class="absolute z-10 left-1/2 transform -translate-x-1/2 mt-3 px-2 w-screen max-w-xs sm:px-0">
            <div class="rounded-lg shadow-lg ring-1 ring-black ring-opacity-5 overflow-hidden">
              <div class="relative grid gap-6 bg-black px-5 py-6 sm:gap-8 sm:p-8">
                <a href="#" class="-m-3 p-3 block rounded-md hover:bg-gray-50">
                 <p class="text-base font-medium text-white">
                    Office
                 </p>
                 <p class="mt-1 text-sm text-gray-500">
                    Get all of your questions answered in our forums or contact support.
                 </p>
                </a>

                <a href="#" class="-m-3 p-3 block rounded-md hover:bg-gray-50">
                 <p class="text-base font-medium text-white">
                    Navegacion
                 </p>
                 <p class="mt-1 text-sm text-gray-500">
                    Learn how to maximize our platform to get the most out of it.
                 </p>
                </a>

                <a href="#" class="-m-3 p-3 block rounded-md hover:bg-gray-50">
                 <p class="text-base font-medium text-white">
                    Redes
                 </p>
                 <p class="mt-1 text-sm text-gray-500">
                    See what meet-ups and other events we might be planning near you.
                 </p>
                </a>

                <a href="#" class="-m-3 p-3 block rounded-md hover:bg-gray-50">
                 <p class="text-base font-medium text-white">
                    Seguridad
                 </p>
                 <p class="mt-1 text-sm text-gray-500">
                    Understand how we take your privacy seriously.
                 </p>
                </a>
              </div>
            </div>
          </div>
        </div>
      </nav>

      <div class="flex items-center md:ml-12">
        {% if user.is_authenticated %}
        <!-- This example requires Tailwind CSS v2.0+ -->
        <div x-data="{open:false}" class="relative inline-block text-left">
            <div @click="open=true">
                <img class="inline-block h-10 w-10 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
            </div>

            <div x-show="open" @click.away="open=false" class="origin-top-right absolute right-0 mt-2 w-56 rounded-md shadow-lg bg-black ring-1 ring-black ring-opacity-5 divide-y divide-gray-100 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="menu-button" tabindex="-1">
                <div class="px-4 py-3" role="none">
                <p class="text-sm text-white" role="none">
                  Registrado como
                </p>
                <p class="text-sm font-medium text-white truncate" role="none">
                    tom@example.com
                </p>
                </div>
                <div class="py-1" role="none">
                <!-- Active: "bg-gray-100 text-gray-900", Not Active: "text-gray-700" -->
                <a href="{% url 'account_change_password' %}" class="text-gray-700 block px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="menu-item-0">Security</a>
                <a href="#" class="text-gray-700 block px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="menu-item-1">Support</a>
                <a href="" class="text-gray-700 block px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="menu-item-2">Subscription</a>
                </div>
                <div class="py-1" role="none">
                <form method="POST" action="{% url 'account_logout' %}" role="none">
                    {% csrf_token %}
                    <button type="submit" class="text-gray-700 block w-full text-left px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="menu-item-3">
                      desconectar
                    </button>
                </form>
                </div>
            </div>
        </div>

        {% else %}
        <a href="{% url 'account_login' %}" class="text-base font-medium text-white hover:text-gray-500">
          Iniciar sesión
        </a>
        <a href="{% url 'account_signup' %}" class="ml-8 inline-flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-indigo-600 hover:bg-indigo-700">
          Inscribirse
        </a>
        {% endif %}
        
      </div>


    </div>
  </div>

  <!--
    Mobile menu, show/hide based on mobile menu state.
  -->
  <div x-show="open" @click.away="open=false"
    x-transition:enter="ease-out duration-300" x-transition:enter-start="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95" x-transition:enter-end="opacity-100 translate-y-0 sm:scale-100" x-transition:leave="ease-in duration-200" x-transition:leave-start="opacity-100 translate-y-0 sm:scale-100" x-transition:leave-end="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
   class="absolute top-0 inset-x-0 p-2 transition transform origin-top-right md:hidden">
    <div class="rounded-lg shadow-lg ring-1 ring-black ring-opacity-5 bg-white divide-y-2 divide-gray-50">
      <div class="pt-5 pb-6 px-5">
        <div class="flex items-center justify-between">
          <div>
            <img class="h-8 w-auto" src="https://tailwindui.com/img/logos/workflow-mark-indigo-600.svg" alt="Workflow">
          </div>
          <div class="-mr-2">
            <button @click="open=false" type="button" class="bg-white rounded-md p-2 inline-flex items-center justify-center text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500">
              <span class="sr-only">Close menu</span>
              <!-- Heroicon name: outline/x -->
              <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
        </div>
        <div class="mt-6">
          <nav class="grid gap-6">
            <a href="#" class="-m-3 p-3 flex items-center rounded-lg hover:bg-gray-50">
              <div class="flex-shrink-0 flex items-center justify-center h-10 w-10 rounded-md bg-indigo-500 text-white">
                <!-- Heroicon name: outline/chart-bar -->
                <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
                </svg>
              </div>
              <div class="ml-4 text-base font-medium text-gray-900">
                Analytics
              </div>
            </a>


          </nav>
        </div>
      </div>
      <div class="py-6 px-5">
        <div class="grid grid-cols-2 gap-4">
          <a href="#" class="text-base font-medium text-gray-900 hover:text-gray-700">
            precios
          </a>

          <a href="#" class="text-base font-medium text-gray-900 hover:text-gray-700">
            Docs
          </a>

          <a href="#" class="text-base font-medium text-gray-900 hover:text-gray-700">
            Enterprise
          </a>

          <a href="#" class="text-base font-medium text-gray-900 hover:text-gray-700">
            Help Center
          </a>

          <a href="#" class="text-base font-medium text-gray-900 hover:text-gray-700">
            Guides
          </a>

          <a href="#" class="text-base font-medium text-gray-900 hover:text-gray-700">
            Events
          </a>

          <a href="#" class="text-base font-medium text-gray-900 hover:text-gray-700">
            Security
          </a>
        </div>
        <div class="mt-6">
          <a href="#" class="w-full flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-indigo-600 hover:bg-indigo-700">
            Inscribirse
          </a>
          <p class="mt-6 text-center text-base font-medium text-gray-500">
            Existing customer?
            <a href="#" class="text-indigo-600 hover:text-indigo-500">
              desconectar
            </a>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>