core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('courses/', include('courses.urls', namespace="courses")),
    path('payment/', include('payment.urls', namespace="payment")),

    path('', HomeView.as_view(), name="home")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

courses/models.py
from django.db import models
from django.db.models.fields.related import ForeignKey, ManyToManyField
from django.utils import timezone
from django.shortcuts import reverse
from django.conf import settings
import stripe
stripe.api_key = settings.STRIPE_SECRET_KEY


from allauth.account.signals import email_confirmed


from django.contrib.auth import get_user_model
User = get_user_model()

# Create your models here.
def user_directory_path(instance,filename):
    return 'courses/{0}/{1}'.format(instance.title, filename)

def chapter_directory_path(instance, filename):
    return 'courses/{0}/{1}/{2}'.format(instance.course, instance.title, filename)

def lesson_directory_path(instance, filename):
    return 'courses/{0}/{1}/Lesson #{2}: {3}/{4}'.format(instance.course, instance.chapter, instance.lesson_number,instance.title, filename)

class Author(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Pricing(models.Model):
    name= models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    stripe_price_id = models.CharField(max_length=50)
    price = models.DecimalField(decimal_places=2, max_digits=5)
    currency = models.CharField(max_length=50)

    def __str__(self):
        return self.name



class Subscription(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    pricing = models.ForeignKey(Pricing, on_delete=models.CASCADE, related_name='subscriptions')
    created = models.DateTimeField(auto_now_add=True)
    stripe_subscription_id = models.CharField(max_length=50)
    status = models.CharField(max_length=100)
    
    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.user.email

    @property
    def is_active(self):
        return self.status == "active" or self.status == "trialing"


class Course(models.Model):
    authors = ManyToManyField(Author)
    pricing_tiers = models.ManyToManyField(Pricing, blank=True)
    title = models.CharField(max_length=100)
    sub_title = models.CharField(max_length=100)
    thumbnail = models.ImageField(upload_to=user_directory_path, blank=True, null=True)
    video = models.FileField(upload_to=user_directory_path)
    vimeo_video = models.CharField(verbose_name="Vimeo Video ID (Optional)",max_length=100, blank=True, null=True)
    slug = models.SlugField(max_length=250, unique_for_date='published', null=False, unique=True)
    published = models.DateTimeField(default=timezone.now)
    is_active=models.BooleanField(default=True)

    class Meta:
        ordering = ('-published',)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("courses:detail", kwargs={
            'slug': self.slug
        })
    
def post_email_confirmed(request, email_address, *args, **kwargs):
    user = User.objects.get(email=email_address.email)
    free_trial_pricing = Pricing.objects.get(name='academico')

    subscription = Subscription.objects.create(
        user=user,
        pricing=free_trial_pricing
    )

    #Crear cliente en stripe
    stripe_customer = stripe.Customer.create(
        email=user.email
    )

    stripe_subscription = stripe.Subscription.create(
        customer=stripe_customer["id"],
        items=[{'price': 'price_1P50MFAZTeS0T67Kdzh6KLht'}],
        trial_period_days=7
    )

    subscription.status=stripe_subscription["status"]
    subscription.stripe_subscription_id = stripe_subscription["id"]
    subscription.save()
    user.stripe_customer_id=stripe_customer["id"]
    user.save()


class Chapter(models.Model):
    course = ForeignKey(Course, on_delete=models.CASCADE, blank=True, null=True)
    chapter_number = models.IntegerField(blank=True, null=True)
    title = models.CharField(max_length=100)
    thumbnail = models.ImageField(upload_to=chapter_directory_path)
    video = models.FileField(upload_to=chapter_directory_path)
    vimeo_video = models.CharField(verbose_name="Vimeo Video ID (Optional)",max_length=100, blank=True, null=True)
    content = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("courses:chapter-detail", kwargs={
            'course_slug': self.course.slug,
            'chapter_number': self.chapter_number,
        })

class Lesson(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE,blank=True, null=True)
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE,blank=True, null=True)
    lesson_number = models.IntegerField(blank=True, null=True)
    title = models.CharField(max_length=100)
    thumbnail = models.ImageField(upload_to=lesson_directory_path, default='courses/default.jpg')
    video = models.FileField(upload_to=lesson_directory_path)
    vimeo_video = models.CharField(verbose_name="Vimeo Video ID (Optional)",max_length=100, blank=True, null=True)
    content = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("courses:lesson-detail", kwargs={
            'course_slug': self.chapter.course.slug,
            'chapter_number': self.chapter.chapter_number,
            'lesson_number': self.lesson_number
        })

email_confirmed.connect(post_email_confirmed)

templates/courses/pages/course/detail.html
{% extends 'base.html' %}

{% block title %}{% endblock title %}
{% block extra_head %}{% endblock extra_head %}

{% block navbar %}
{% endblock navbar %}


{% block content %}

<!-- This example requires Tailwind CSS v2.0+ -->
<div x-data="{open:false}" class="h-screen flex overflow-hidden bg-gray-100">
  <!-- MOBILE  -->
  <div x-show="open"  class="fixed inset-0 flex z-40 md:hidden" role="dialog" aria-modal="true">
    <!--
      Off-canvas menu overlay, show/hide based on off-canvas menu state.

      Entering: "transition-opacity ease-linear duration-300"
        From: "opacity-0"
        To: "opacity-100"
      Leaving: "transition-opacity ease-linear duration-300"
        From: "opacity-100"
        To: "opacity-0"
    -->
    <div @click="open=false" x-show="open" class="fixed inset-0 bg-gray-600 bg-opacity-75" x-transition:enter="transition-opacity ease-linear duration-300" x-transition:enter-start="opacity-0" x-transition:enter-end="opacity-100" x-transition:leave="transition-opacity ease-linear duration-300" x-transition:leave-start="opacity-100" x-transition:leave-end="opacity-0" aria-hidden="true"></div>

    <!--
      Off-canvas menu, show/hide based on off-canvas menu state.

      Entering: "transition ease-in-out duration-300 transform"
        From: "-translate-x-full"
        To: "translate-x-0"
      Leaving: "transition ease-in-out duration-300 transform"
        From: "translate-x-0"
        To: "-translate-x-full"
    -->
    <div class="relative flex-1 flex flex-col max-w-xs w-full bg-white" x-show="open"  x-transition:enter="transition ease-in-out duration-300 transform" x-transition:enter-start="-translate-x-full" x-transition:enter-end="translate-x-0" x-transition:leave="transition ease-in-out duration-300 transform" x-transition:leave-start="translate-x-0" x-transition:leave-end="-translate-x-full">
      <!--
        Close button, show/hide based on off-canvas menu state.

        Entering: "ease-in-out duration-300"
          From: "opacity-0"
          To: "opacity-100"
        Leaving: "ease-in-out duration-300"
          From: "opacity-100"
          To: "opacity-0"
      -->
      <div class="absolute top-0 right-0 -mr-12 pt-2">
        <button @click="open=false" type="button" class="ml-1 flex items-center justify-center h-10 w-10 rounded-full focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white">
          <span class="sr-only">Close sidebar</span>
          <!-- Heroicon name: outline/x -->
          <svg class="h-6 w-6 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>

      <div class="flex-1 h-0 pt-5 pb-4 overflow-y-auto">
        
        <nav class="mt-5 px-2 space-y-1">

            <a href="{% url 'home' %}" class=" inline-flex items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded text-indigo-700 bg-indigo-100 hover:bg-indigo-200 ">
              Regresar
            </a>

          <!-- Current: "bg-gray-100 text-gray-900", Default: "text-gray-600 hover:bg-gray-50 hover:text-gray-900" -->
            <a href="{{course.get_absolute_url}}" class=" {% if request.path == course.get_absolute_url %} bg-gray-100 text-gray-900 group flex items-center px-2 py-2 text-sm font-medium rounded-md {%else%} text-gray-600 hover:bg-gray-50 hover:text-gray-900 group flex items-center px-2 py-2 text-sm font-medium rounded-md {%endif%}">
              <!--
                Heroicon name: outline/home

                Current: "text-gray-500", Default: "text-gray-400 group-hover:text-gray-500"
              -->
              <svg class="text-gray-500 mr-3 flex-shrink-0 h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
              </svg>
              {{course.title}}
            </a>

            {% for chapter in course.chapter_set.all %}
            <a href="{{chapter.get_absolute_url}}" class="{% if request.path == chapter.get_absolute_url %} bg-gray-100 text-gray-900 group flex items-center px-2 py-2 text-sm font-medium rounded-md {%else%} text-gray-600 hover:bg-gray-50 hover:text-gray-900 group flex items-center px-2 py-2 text-sm font-medium rounded-md {%endif%}">
              <!-- Heroicon name: outline/users -->
              <span class="text-gray-500 font-medium">{{chapter.chapter_number}}) {{chapter.title}}</span>
            </a>

              {% for lesson in chapter.lesson_set.all %}
              <a href="{{lesson.get_absolute_url}}" class="{% if request.path == lesson.get_absolute_url %} bg-gray-100 text-gray-900 group flex items-center px-2 py-2 text-sm font-medium rounded-md {%else%} text-gray-600 hover:bg-gray-50 hover:text-gray-900 group flex items-center px-2 py-2 text-sm font-medium rounded-md {%endif%}">
                <!-- Heroicon name: outline/users -->
                <span class="text-gray-500 font-medium">{{lesson.title}}</span>
              </a>
              {% endfor %}
            
            {% endfor %}
        </nav>
      </div>

    </div>

    <div class="flex-shrink-0 w-14">
      <!-- Force sidebar to shrink to fit close icon -->
    </div>
  </div>

  <!-- DESKTOP -->
  <div class="hidden md:flex md:flex-shrink-0">
    <div class="flex flex-col w-64">
      <!-- Sidebar component, swap this element with another sidebar if you like -->
      <div class="flex-1 flex flex-col min-h-0 border-r border-gray-200 bg-white">
        <div class="flex-1 flex flex-col pt-5 pb-4 ">

          
          
          <nav class="mt-5 flex-1 px-2 bg-white space-y-1 overflow-y-auto">

            <a href="{% url 'home' %}" class=" inline-flex items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded text-indigo-700 bg-indigo-100 hover:bg-indigo-200">
              Regresar
            </a>
            <!-- Current: "bg-gray-100 text-gray-900", Default: "text-gray-600 hover:bg-gray-50 hover:text-gray-900" -->
            <a href="{{course.get_absolute_url}}" class=" {% if request.path == course.get_absolute_url %} bg-gray-100 text-gray-900 group flex items-center px-2 py-2 text-sm font-medium rounded-md {%else%} text-gray-600 hover:bg-gray-50 hover:text-gray-900 group flex items-center px-2 py-2 text-sm font-medium rounded-md {%endif%}">
              <!--
                Heroicon name: outline/home

                Current: "text-gray-500", Default: "text-gray-400 group-hover:text-gray-500"
              -->
              <svg class="text-gray-500 mr-3 flex-shrink-0 h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
              </svg>
              {{course.title}}
            </a>

            {% for chapter in course.chapter_set.all %}
            <a href="{{chapter.get_absolute_url}}" class="{% if request.path == chapter.get_absolute_url %} bg-gray-100 text-gray-900 group flex items-center px-2 py-2 text-sm font-medium rounded-md {%else%} text-gray-600 hover:bg-gray-50 hover:text-gray-900 group flex items-center px-2 py-2 text-sm font-medium rounded-md {%endif%}">
              <!-- Heroicon name: outline/users -->
              <span class="text-gray-500 font-medium">{{chapter.chapter_number}}) {{chapter.title}}</span>
            </a>

              {% for lesson in chapter.lesson_set.all %}
              <a href="{{lesson.get_absolute_url}}" class="{% if request.path == lesson.get_absolute_url %} bg-gray-100 text-gray-900 group flex items-center px-2 py-2 text-sm font-medium rounded-md {%else%} text-gray-600 hover:bg-gray-50 hover:text-gray-900 group flex items-center px-2 py-2 text-sm font-medium rounded-md {%endif%}">
                <!-- Heroicon name: outline/users -->
                <span class="text-gray-500 font-medium">{{lesson.title}}</span>
              </a>
              {% endfor %}
            
            {% endfor %}
            

            

          </nav>
        </div>


      </div>
    </div>
  </div>


  <div class="flex flex-col w-0 flex-1 overflow-hidden">
    <div class="md:hidden pl-1 pt-1 sm:pl-3 sm:pt-3">
      <button @click="open=true" type="button" class="-ml-0.5 -mt-0.5 h-12 w-12 inline-flex items-center justify-center rounded-md text-gray-500 hover:text-gray-900 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500">
        <span class="sr-only">Open sidebar</span>
        <!-- Heroicon name: outline/menu -->
        <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
        </svg>
      </button>
    </div>

    <!-- CONTENT -->
    <main class="flex-1 relative z-0 overflow-y-auto focus:outline-none">
      <div class="py-6">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 md:px-8">
          <h1 class="text-2xl font-semibold text-gray-900">{{course.title}}</h1>
        </div>

        <div class="max-w-7xl mx-auto px-4 sm:px-6 md:px-8">
          <!-- Replace with your content -->
          <video class="my-1 items-center justify-center p-4 inline-flex video-js vjs-16-9"
              id="{{post.id}}"
              controls
              preload="auto"
              data-setup="{'playbackRates': [0.5, 1, 1.5, 2], 'fluid': true}"
              >
              <source src="{{ course.video.url }}" type="video/mp4" />
              <p class="vjs-no-js dark:text-dark-txt text-gray-500">
              To view this video please enable JavaScript, and consider upgrading to a
              web browser that
              <a href="https://videojs.com/html5-video-support/" target="_blank"
                  >supports HTML5 video</a
              >
              </p>
          </video>

          <div class="relative py-16 mt-4 overflow-hidden">
            <div class="relative px-4 sm:px-6 lg:px-8">
              <div class="text-lg max-w-prose mx-auto">
                <h1>
                  <span class="block text-base text-center text-indigo-600 font-semibold tracking-wide uppercase">Category</span>
                  <span class="mt-2 block text-3xl text-center leading-8 font-extrabold tracking-tight text-gray-900 sm:text-4xl">{{course.title}}</span>
                </h1>
                <p class="mt-8 text-xl text-gray-500 leading-8">{{course.sub_title}}</p>
              </div>
              <div class="mt-6 prose prose-indigo prose-lg text-gray-500 mx-auto">
                <p>test</p>
              </div>
            </div>
          </div>

          <!-- /End replace -->
        </div>
      </div>
    </main>
  </div>
</div>


{% endblock content %}
    

{% block footer %}

{% endblock footer %}

{% block javascript %}{% endblock javascript %}